### ISSUE TITLE
option to allow larger VMs 

### ISSUE THREAD

**Issue by arubdesu** [chilcote/vfuse#14]
I believe the manual override you can perform at this time(was it @golby who was tweeting about this?) is to modify it with vdiskmanager here: https://github.com/chilcote/vfuse/blob/master/vfuse#L182-L187
Sorry I'm not leading with a PR, hope this is a good placeholder for someone to confirm the above is correct in the meantime.

**Comment by chilcote** [comment]
I confused a different issue with this when we discussed it at MacDevOps.

It looks like it's possible to resize the disk with vmware-vdiskmanager -x N

However, the issue still remains that the volume will need to be resized within the VM itself (using Disk Utility).  

I wonder if it's better to simply increase the size of the DMG when creating it with AutoDMG, etc?

**Comment by chilcote** [comment]
The size is determined by the autodmg image itself.
