### ISSUE TITLE
"File not found" when launching vfuse-produced VMs for the first time

### ISSUE THREAD

**Issue by homebysix** [chilcote/vfuse#22]
I created a 10.8 VM with vfuse, starting with a plain 10.8 AutoDMG.

```
Mounting ~/osx10.8.5-12F45-generic.hfs.dmg
OS X version is 10.8.5
Converting DMG to VMDK
Populating VMX file
Unmounting Base OS DMG
VMware Fusion VM created at ~/Documents/Virtual Machines.localized/vFuse Mac OS X 10.8.vmwarevm
```

However, upon launching the VM, I get this:

![screen shot 2015-12-03 at 2 43 55 pm](https://cloud.githubusercontent.com/assets/7801391/11576549/4e006d10-99cc-11e5-80fe-9b596342aae2.png)

Clicking Browse doesn't reveal any .vmdk files to choose from:
![screen shot 2015-12-03 at 2 46 33 pm](https://cloud.githubusercontent.com/assets/7801391/11576612/c4f36dd2-99cc-11e5-9c59-d6cd6b99db82.png)

My host Mac has 10.10.1 and VMware Fusion 8.0.2, and is up to date with vfuse commit 12960d7.

Anything I can try to troubleshoot?

**Comment by chilcote** [comment]
I haven't been able to replicate this particular issue, but your example from slack pointed me to a different issue with how the path expansion is happening.

**Comment by ryandesign** [comment]
I see similar:

```
Mounting osx_custom_151220-10.11.2-15C50.hfs.dmg
OS X version is 10.11.2
VMware hardware version 8 does not officially support 10.11
Using VMware Fusion path: /Applications/VMware Fusion.app
Converting DMG to VMDK
Populating VMX file
Unmounting Base OS DMG
VMware Fusion VM created at ./osx_custom_151220-10.11.2-15C50.vmwarevm
```

But ./osx_custom_151220-10.11.2-15C50.vmwarevm/osx_custom_151220-10.11.2-15C50.vmdk was not created.

I assume `vmware-rawdiskCreator` or `vmware-vdiskmanager` encountered an error during the attempt to convert, but vfuse did not detect or report the error. When I tried running the relevant `vmware-vdiskmanager` command manually, I received an illuminating error message:

```
Failed to convert disk: An error occurred while writing a file; the disk is full. Data has not been saved. Free some disk space and try again (0x8).
```

**Comment by chilcote** [comment]
How much free space do you have on your disk?

**Comment by ryandesign** [comment]
Certainly not enough!

**Comment by chilcote** [comment]
Fair 'nuff. I'll do some tests.

**Comment by ryandesign** [comment]
It's working fine now that I've pointed it at a disk with enough free space. vfuse should detect and report errors thrown by `vmware-vdiskmanager` and not continue on as if nothing happened.

**Comment by chilcote** [comment]
try the latest commit, as it will now report the error and exit.

**Comment by homebysix** [comment]
Guess what, it's working for me now! The .vmdk file is present inside the bundle, as expected, and the VM boots successfully.

In addition to updating to the latest commit, I also re-downloaded the source AutoDMG file. I suspect it (and others) may have been corrupted.

**Comment by ryandesign** [comment]
Thank you @chilcote, error reporting is working now:

```
Mounting osx_custom_151220-10.11.2-15C50.hfs.dmg
OS X version is 10.11.2
VMware hardware version 8 does not officially support 10.11
Using VMware Fusion path: /Applications/VMware Fusion.app
Converting DMG to VMDK
Error: Failed to convert disk: An error occurred while writing a file; the disk is full. Data has not been saved. Free some disk space and try again (0x8).
Unmounting Base OS DMG
```

It does still leave a \*.vmwarevm folder containing a disk\*-link.vmdk file; maybe those could be cleaned up in case an error occurs.

**Comment by chilcote** [comment]
Should remove the vmpath now with the last commit, thanks.
