### ISSUE TITLE
Detecting VMware Fusion installs in locations besides /Applications

### ISSUE THREAD

**Issue by timsutton** [chilcote/vfuse#23]
..for example, if you install Fusion via brew-cask, you'll have somewhere in `/opt/caskroom` and a symlink in `~/Applications/VMware Fusion.app`.

Would you consider a PR to support alternate install directories? This could be done either by:

1. A manually-set option
1. Using Spotlight: `cmd = ['/usr/bin/mdfind', 'kMDItemCFBundleIdentifier == com.vmware.fusion']` and picking the first result.

**Comment by chilcote** [comment]
What happens if someone has a tech preview installed, or multiple versions of Fusion.

**Comment by chilcote** [comment]
answered my own question

**Comment by timsutton** [comment]
Thanks for addressing this so quickly. How do you think it's best to handle the case where there might be multiple versions, though? If someone has the tech preview, for example, and you have a glob on `/Applications/VMware Fusion*`, which one returns first? Just wondering if it might cause unexpected issues.

**Comment by chilcote** [comment]
There will always be problems.  I'm sure there is someone out there who disables spotlight and wants to run Fusion from /System/Library/Extensions and is writing up their screed this very second.

The mdfind will sort the results, so it will prefer any in /Applications.

I have it reporting which version of Fusion is being used, too, so one can always define the correct one in a template. I thought about having it ask the operator to choose from a list, but that would annoy me. In the end.
