### ISSUE TITLE
Option to add a 'qemu-img' mode?

### ISSUE THREAD

**Issue by timsutton** [chilcote/vfuse#24]
Thanks to a tip from @morgrowe, I learned it's possible to use the [qemu-img](http://linux.die.net/man/1/qemu-img) to convert a DMG to a VMDK, without a need for VMware Fusion or `sudo`, and only `qemu` from homebrew. I tested swapping in the command into `vfuse` in place of the two `vmware-` tools and let it set up the rest of the `.vmwarevm` file as usual, and it works.

The length of time required to convert the image is nearly identical. Would you be interested in a PR that would add this as an alternate "mode" for vfuse? This means it would skip the check for running as root and for VMware, as neither of those things should be required. (As you might guess I like the lack of those requirements, as least for the case of generating this image on a throwaway machine that may not have VMware installed.)

**Comment by timsutton** [comment]
To test this:

```bash
brew install qemu
qemu-img convert -O vmdk /path/to/autodmg.hfs.dmg /path/to/output.vmdk
```

**Comment by chilcote** [comment]
I'm all for it, especially if it provides virtualbox support.
