### ISSUE TITLE
Creating thin provisioned VM for ESXi need remote destination

### ISSUE THREAD

**Issue by ygini** [chilcote/vfuse#26]
Hi

I need to create a thin provisioned disk to use with vSphere. It's the disk option 6.

Here is the template I've used:

```
{
    "source_dmg": "/Users/yoann/Pro/SystemImage/osx_updated_160626-10.11.5-15F34.hfs.dmg",
    "output_dir": "/Users/yoann/Pro/vSphereTemplate",
    "output_name": "OS X 10.11.5",
    "cache": false,
    "hw_version": 11,
    "mem_size": 2048,
    "disk_type": 6,
    "bridged": false,
    "hw_model": "11",
    "use_qemu": false
}
```

And here is the run log:

```
If you don't want to be prompted in the GUI for an admin password, run this script with sudo rights

Mounting /Users/yoann/Pro/SystemImage/osx_updated_160626-10.11.5-15F34.hfs.dmg
OS X version is 10.11.5
VMware hardware version 11 does not officially support 10.11
Using VMware Fusion path: /Applications/VMware Fusion.app
Converting DMG to VMDK
Error: VMware Virtual Disk Manager can only convert to ESX thin disks if the destination is remote.
Unmounting Base OS DMG
```

According to the VMware documentation the right command to use is ```vmware-vdiskmanager -r sourceDisk.vmdk -t 4 -h esx3.example.com -u root -f password.txt "[storage1] <VMname>/targetDisk.vmdk"```

https://pubs.vmware.com/vsphere-50/index.jsp?topic=%2Fcom.vmware.vddk.utils.doc_50%2Fdiskutils_diskmgr.5.4.html

**Comment by chilcote** [comment]
If you run this manually against the vmdk created with vfuse (using type 4) what is the result?

vmware-vdiskmanager -r sourceDisk.vmdk -t 6 -h esx4.example.com -u root -f password.txt "[storage1] <VMname>/targetDisk.vmdk

**Comment by ygini** [comment]
I've tried but it seems to not work even if the -h option is in the vmware-vdiskmanager help.

I'm wondering if I done something wrong:

```
"/Applications/VMware Fusion.app/Contents/Library/vmware-vdiskmanager" -r disk2-link.vmdk -t 4 -h 10.2.251.2 -u root -f password.txt "[ds_local_esxi1]/10.11.5/10.11.5.vmdk"
```

**Comment by chilcote** [comment]
I seem to remember that thin provisioned os x guests wasn't supported. When did this change?

**Comment by chilcote** [comment]
Saw this thread with Michael Roy. We can track the status of that request with VMware and then return to this issue. https://twitter.com/mikeroysoft/status/752578192456626176
