### ISSUE TITLE
Error when escaping a path in template

### ISSUE THREAD

**Issue by ftiff** [chilcote/vfuse#27]
When i escape a directory in the template, I get a ValueError

Example with **"output_dir": "/Users/fti/Documents/Virtual\ Machines.localized",**

> berry:~ $ /usr/local/vfuse/vfuse -t /Volumes/SONY_16X/2-vfuse_vanilla_template.json 
> If you don't want to be prompted in the GUI for an admin password, run this script with sudo rights
> 
> Traceback (most recent call last):
>   File "/usr/local/vfuse/vfuse", line 649, in <module>
>     main()
>   File "/usr/local/vfuse/vfuse", line 526, in main
>     d = import_template(args.template)
>   File "/usr/local/vfuse/vfuse", line 77, in import_template
>     d = json.load(f)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
>     **kw)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
>     return _default_decoder.decode(s)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
>     obj, end = self.scan_once(s, idx)
> ValueError: Invalid \escape: line 3 column 48 (char 137)
> berry:~ $

**Comment by erikng** [comment]
Why are you using \ in the templates? It's going to interpret it as a string.

On Jul 27, 2016, at 11:29 PM, Francois Levaux-Tiffreau <notifications@github.com<mailto:notifications@github.com>> wrote:


When i escape a directory in the template, I get a ValueError

Example with "output_dir": "/Users/fti/Documents/Virtual\ Machines.localized",

berry:~ $ /usr/local/vfuse/vfuse -t /Volumes/SONY_16X/2-vfuse_vanilla_template.json
If you don't want to be prompted in the GUI for an admin password, run this script with sudo rights

Traceback (most recent call last):
File "/usr/local/vfuse/vfuse", line 649, in
main()
File "/usr/local/vfuse/vfuse", line 526, in main
d = import_template(args.template)
File "/usr/local/vfuse/vfuse", line 77, in import_template
d = json.load(f)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/init.py", line 290, in load
**kw)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/init.py", line 338, in loads
return _default_decoder.decode(s)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
obj, end = self.scan_once(s, idx)
ValueError: Invalid \escape: line 3 column 48 (char 137)
berry:~ $

-

**Comment by ftiff** [comment]
Hi @erikng,

Sorry I was on the phone I preferred to quickly log it rather than forget it :)

I understand I shouldn't escape, it was a mistake by doing a copy/paste.
The issue here is more about handling this a bit nicer for the user. 

What do you think?

**Comment by chilcote** [comment]
Agreed.

**Comment by ftiff** [comment]
thanks!
