### ISSUE TITLE
Obsolete warning message in vFuse about macOS Sierra and HW12

### ISSUE THREAD

**Issue by rtrouton** [chilcote/vfuse#29]
VMware Fusion 8.5 has been released with an option to create macOS Sierra VMs. Sierra VMs are using Hardware Version 12, so it should no longer be necessary to have the following warning message in `vfuse`:

`VMware hardware version 12 does not officially support 10.12`

![screen shot 2016-09-13 at 1 03 39 pm](https://cloud.githubusercontent.com/assets/618055/18483598/b2ae452c-79b2-11e6-9624-4a39078d4eab.png)

**Comment by chilcote** [comment]
Thanks Sparky.  Downloading 8.5 now... will have an update by EOD.

**Comment by chilcote** [comment]
Can you try https://github.com/chilcote/vfuse/tree/fusion8.5 please?

**Comment by chilcote** [comment]
Should be good
