### ISSUE TITLE
Template option to specify VM build path when using Netboot option

### ISSUE THREAD

**Issue by mark-cohen** [chilcote/vfuse#38]
When using a vfuse template to build a Netboot ready VM, it would be great to have the ability to specify the (temp) build path. While the default is understandably "/tmp/", this can be problematic if adequate space isnt available. 

Perhaps something akin to: 
"tmp_dir": "/Volumes/PlentyoSpace/VMs/",

Thanks.

**Comment by chilcote** [comment]
Hi Mark.

Can you try the branch at https://github.com/chilcote/vfuse/tree/netboot_tmp_dir please? The key for the template is "netboot_tmp_dir".

**Comment by chilcote** [comment]
@mark-cohen Did you ever have a chance to try this out?

**Comment by chilcote** [comment]
I'm going to assume that this fr is abandoned?

**Comment by chilcote** [comment]
Closing
