### ISSUE TITLE
Errno 2 when building 10.13 VM on 10.13 host machine with VMware Fusion

### ISSUE THREAD

**Issue by smashism** [chilcote/vfuse#44]
We've discussed this a bit in #virtualization on the MacAdmins Slack but I thought I'd open it here so there'd be a record of the issue. When attempting to build a 10.13 VM with VMware Fusion on a 10.13 machine I get the following error:

`[Errno 2] No such file or directory: '/Volumes/Preboot 1/System/Library/CoreServices/SystemVersion.plist'`

**Comment by chilcote** [comment]
fixed with https://github.com/chilcote/vfuse/commit/fb0498571007637699edca0a8d65030a1e375b63
