### ISSUE TITLE
Key Error

### ISSUE THREAD

**Issue by rcohen-interlaced** [chilcote/vfuse#48]
When trying to convert a DMG I'm getting the following returned:

Traceback (most recent call last):
  File "/Users/admin/Downloads/vfuse-master/pkgroot/usr/local/vfuse/vfuse", line 844, in <module>
    main()
  File "/Users/admin/Downloads/vfuse-master/pkgroot/usr/local/vfuse/vfuse", line 746, in main
    mount_point, disk_id, volume_kind = mount_dmg(source_dmg)
  File "/Users/admin/Downloads/vfuse-master/pkgroot/usr/local/vfuse/vfuse", line 144, in mount_dmg
    if i['content-hint'] == 'GUID_partition_scheme':
KeyError: 'content-hint'

I'm unsure what this means or how to resolve it.

**Comment by chilcote** [comment]
if you run `/usr/bin/hdiutil attach /path/to/the/dmg -plist` what does it return?

**Comment by rcohen-interlaced** [comment]
sorry should have stated earlier this is on macOS

**Comment by rcohen-interlaced** [comment]
hdiutil attach /Volumes/Rick\ USB-C/Steve\ Spare\ Laptop\ copy.dmg 

expected   CRC32 $31168D6D

/dev/disk5          	                               	/Volumes/Macintosh HD 1

**Comment by chilcote** [comment]
Try with the `-plist` option too.  I want to see what the output of that is so I can compare against what's expected.

Also, is this a DMG that was created with Disk Utility from another Mac over thunderbolt?  If so you may be running into this: https://github.com/chilcote/vfuse#caveats

**Comment by rcohen-interlaced** [comment]
It is a DMG of an existing Mac that I'm trying to convert to a VM for a user. I saw the caveat and hoped I'd get lucky to be honest. Created with Disk Utility to a USB-C external drive.


<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>system-entities</key>
	<array>
		<dict>
			<key>dev-entry</key>
			<string>/dev/disk5</string>
			<key>mount-point</key>
			<string>/Volumes/Macintosh HD 1</string>
			<key>potentially-mountable</key>
			<true/>
			<key>volume-kind</key>
			<string>hfs</string>
		</dict>
	</array>
</dict>
</plist>

**Comment by chilcote** [comment]
Yeah that might be it since vfuse is looking for a lot more diskutil info than that. 

What you might could do is create a VM (from an autodmg output) and boot to recovery, then `asr` restore this backed up dmg to `/Volumes/Macintosh HD`

**Comment by rcohen-interlaced** [comment]
Ah well, was worth a try. Thanks for the assistance!
