### ISSUE TITLE
hardware version 14

### ISSUE THREAD

**Issue by erikng** [chilcote/vfuse#50]
latest vmware fusion uses hardware version 14. vfuse should use this version to reduce the "would you like to upgrade this machine?" message every time when booting up a vm.

**Comment by clburlison** [comment]
* Make sure you have updated your template file to remove the `hw_version` key - https://github.com/chilcote/vfuse/pull/45
* Make sure you are on the latest version of `vfuse` (1.0.6) - https://github.com/chilcote/vfuse/blob/1.0.6/pkgroot/usr/local/vfuse/vfuse#L556

**Comment by erikng** [comment]
Apologies. It was my templates.

Thanks,
Erik Gomez
________________________________
