### ISSUE TITLE
High Sierra wont work with shared folders vagrant box

### ISSUE THREAD

**Issue by kbotnen** [chilcote/vfuse#51]
ref: https://github.com/chilcote/vfuse/wiki/Vagrant

When creating my new 10.13 Vagrantbox I got some issue with hgfs not loaded and therefor shared folders not available.

The reason:

Kernel Extensions will not load, because kexts are blocked awaiting userconsent.

The fix:

Before you build your image with AutoDMG do the following modification to the vagrant-outset package.

add the following script in: vagrant-outset/pkgroot/usr/local/outset/boot-every/disable_kext_userconsent.sh
<code>
#!/bin/bash

#Disable kernel extensiopn approving
/usr/sbin/spctl --disable
</code>
Remember to chmod a+x on the script.

then build a new version of vagrant-outset: make pkg

Add this to the packagearray in autodmg and proceed with the instructions on the https://github.com/chilcote/vfuse/wiki/Vagrant

K

**Comment by chilcote** [comment]
I don't think that will work to disable UAKEL. You need to do that from Recovery or a non SIP environment. See http://www.modtitan.com/2017/10/lazy-vm-building-hacks-with-autodmg-and.html for a great example on how to do this.
