### ISSUE TITLE
Unable to use the template option (-t) with the full path to a config json file

### ISSUE THREAD

**Issue by wegotoeleven** [chilcote/vfuse#53]
The latest version (2.0.3) fails to build an image when using the full path of a template json file.

1. `vfuse -t /full/path/to/template.json`
2. Error `Unable to find template: /full/path/to/template.json` is received.

**Comment by headmin** [comment]
same here

**Comment by chilcote** [comment]
Can you try https://github.com/chilcote/vfuse/tree/full_paths please?

**Comment by wegotoeleven** [comment]
All good! Thanks :D
