### ISSUE TITLE
Default path for qemu-img

### ISSUE THREAD

**Issue by ygini** [chilcote/vfuse#58]
Hi

Looking at https://github.com/chilcote/vfuse/wiki/Received-signal-11 you say

```First, you need to install qemu-img. Now, you could use homebrew, like an animal. Which is fine. I mean, if you have to. But the more discerning among you will prefer to install it with macports```

Which a perfectly fine point of view :-)

But latter you also say:

```If you don't supply a path, then vfuse will plug its nose and assume you installed it with brew and look for it at /usr/local/bin/qemu-img.```

Why making things simpler for animals and not for people who do things right? :p

More than a troll, I would like to propose to replace the default value by a call to `qemu-img` with no path, and let the system rely on a properly configured `PATH`, regardless of the species of sys admin.

**Comment by chilcote** [comment]
I prefer full paths to relying on PATH. But feel free to submit a PR.
