### ISSUE TITLE
[Errno 2] with 10.14.4

### ISSUE THREAD

**Issue by motionbug** [chilcote/vfuse#59]
Two different builds of 10.14.4

- Install_macOS_10.14.4-18E226.dmg
- Install_macOS_10.14.4-18E2034.dmg

trying to use vfuse with template that worked before creating a new image for 10.14.4

Get the following error.  

Thanks

```
[Errno 2] No such file or directory: '/Volumes/Install macOS Mojave/System/Library/CoreServices/SystemVersion.plist'
```

---

**Update**
**Using the Install_macOS_10.14.3-18D42.dmg there are no issues creating a new VM**

**Comment by motionbug** [comment]
Template file being used and pointing too dmg(s)

{
    "fusion_path": "/path/VMware Fusion.app",
    "source_dmg": "/path/Install_macOS_10.14.4-18E2034.dmg",
    "output_dir": "/path/",
    "output_name": "CLIENT-10.14.3",
    "hw_version": 16,
    "mem_size": 4096,
    "bridged": true,
    "hw_model": "MacBookProXX",
    "snapshot": true,
    "snapshot_name": "preboot",
    "serial_number": "XXXXXXXXX"
}

**Comment by chilcote** [comment]
How did you create these DMGs?  "/Volumes/Install macOS Mojave" sounds like an installer DMG and not a system DMG built with AutoDMG.

**Comment by motionbug** [comment]
Will check @chilcote and try again.

Thanks

**Comment by chilcote** [comment]
any luck?

**Comment by motionbug** [comment]
we can close this.. created new DMG and working

**Comment by dstranathan** [comment]
I an seeing the error "[Errno 2] No such file or directory: '/Volumes/Preboot 1/System/Library/CoreServices/SystemVersion.plist'" with an AutoDMG-generated DMG containing macOS 10.14.5 (build 18F132. Rebuilt it 3 times. 

Vfuse 2.2.1
VMware Fusion Pro 11.1.0
AutoDMG 1.9
Apple "Install macOS Mojave.app" (10.14.5)

**Comment by rbu18** [comment]
I'm facing the same issue " [Errno 2] No such file or directory: '/Volumes/Recovery 1/System/Library/CoreServices/SystemVersion.plist' "
Built the DMG from autodmg (using the app inside the dmg downloaded with installinstallmacos.py)
10.14.5 18F132

**Comment by dstranathan** [comment]
Figured it out - I was performing all of this on a USB flash drive and for some reason the /Volumes/Preboot volume was appearing to vFuse. Chilcote assisted in Slack (and mentioned a long-term fix will prevent/ignore this).

**Comment by milkerson** [comment]
> I'm facing the same issue " [Errno 2] No such file or directory: '/Volumes/Recovery 1/System/Library/CoreServices/SystemVersion.plist' "
> Built the DMG from autodmg (using the app inside the dmg downloaded with installinstallmacos.py)
> 10.14.5 18F132

I had this same issue and dstranathan's solution worked for me.  I Manually mounted the DMG from AutoDMG, then manually unmounted the Preboot partition, then ran the vfuse command again and it went off without a hitch.

**Comment by luflores** [comment]
This is not working for me...perhaps I am doing it wrong. I download Install macOS Mojave.app and moved it to my ~/Downloads folder. Then open it on AutoDMG (Version 1.9 (578)), drag drop. Which cause  the following msg:

- Install will fail due to Apple bug
A bug in the OS installer (radar 43296160) causes installs to fail if the Mojave installer is on the system volume. Copy it to an external volume or wrap it in a dmg before dropping it on AutoDMG.

I then copy the Install macOS Mojave.app to an USB drive and drag drop to AutoDMG. This complete and I run the following command that result in error.

Any idea how I can get around this ?

```
~/Downloads$` sudo /usr/local/vfuse/bin/vfuse -i /Users/luis/Downloads/osx-10.14.5-18F132.apfs.dmg -o /Users/luis/Virtual\ Machines.localized/ -s random --hw-model "MacBookPro13,3" -n "macOS_vfuse"
Password:
Mounting /Users/luis/Downloads/osx-10.14.5-18F132.apfs.dmg
[Errno 2] No such file or directory: '/Volumes/Preboot 1/System/Library/CoreServices/SystemVersion.plist'
Unmounting /Volumes/Preboot 1
```

**Comment by chilcote** [comment]
It appears that having a volume mounted at /Volumes/Preboot is way more common than I thought. I'll have to fix vfuse to be smarter about that. 

In the meantime you can unmount that volume (`diskutil eject /Volumes/Preboot`) and then it shouldn't complain any more.

**Comment by luflores** [comment]
Thanks...no I got the following.

```~/Downloads$ sudo /usr/local/vfuse/bin/vfuse -i /Users/luis/Downloads/osx-10.14.5-18F132.apfs.dmg -o /Users/luis/Virtual\ Machines.localized/ -s random --hw-model "MacBookPro13,3" -n "macOS_ibm"
Password:
Mounting /Users/luis/Downloads/osx-10.14.5-18F132.apfs.dmg
macOS version is 10.14.5
Unmounting /Volumes/Macintosh HD
Using VMware Fusion path: /Applications/VMware Fusion.app
Converting DMG to VMDK
|Error: Unable to create the source raw disk: Resource deadlock avoided (720905).
There is a problem with your DMG; please re-create it and try again
Unmounting /dev/disk12```

I am using Fusion 11.1.0

**Comment by luflores** [comment]
I have recreated the DMG with AutoDMG 3 times :(

**Comment by luflores** [comment]
I use the following and it worked!

```
~/Downloads$ sudo /usr/local/vfuse/bin/vfuse -i /Users/luflores/Downloads/osx-10.14.5-18F132.apfs.dmg -o /Users/luis/Virtual\ Machines.localized/ -s random --hw-model "MacBookPro13,3" -n "macOS_ibm" --use-qemu
Mounting /Users/luis/Downloads/osx-10.14.5-18F132.apfs.dmg
macOS version is 10.14.5
Unmounting /Volumes/Macintosh HD
Using qemu-img path: /usr/local/bin/qemu-img
Converting DMG to VMDK
Populating VMX file
Unmounting /dev/disk12
VMware Fusion VM created at /Users/luflores/Virtual Machines.localized/macOS_ibm.vmwarevm


```

**Comment by rbu18** [comment]
> I'm facing the same issue " [Errno 2] No such file or directory: '/Volumes/Recovery 1/System/Library/CoreServices/SystemVersion.plist' "
> Built the DMG from autodmg (using the app inside the dmg downloaded with installinstallmacos.py)
> 10.14.5 18F132

Reboot and running the command again fixed it for me.

**Comment by chilcote** [comment]
[This](https://github.com/chilcote/vfuse/commit/c9db3b54ec627c10e98d96ab33dc4cfcbbdcba73) should fix this problem
