### ISSUE TITLE
after filvault is enabled through our scripted provisioning and restarts the vm doesnt boot

### ISSUE THREAD

**Issue by tkimpton** [chilcote/vfuse#60]
I can build vms fine with the Model identifier and serial to test out DEP workflows. The issue is after filevault is enabled through our scripted provisioning and restarts the vm blue screens and doesn't boot. This is all macOS versions where the DMG is made with AutoDMG.

We have always had this problem but i have only just got around to logging this now.

**Comment by rickheil** [comment]
We've worked around by blessing the disk. Here's an example script from Erik Gomez: https://github.com/erikng/installapplicationsdemo/blob/master/installapplications/scripts/root/high_sierra_vm_bless.py
