### ISSUE TITLE
Installation of vfuse?

### ISSUE THREAD

**Issue by imasupersadpanda** [chilcote/vfuse#62]
Heya... I'm sure this is just about the dumbest question regarding vfuse you've received. I'm new to github and have no idea how to install vfuse so that I can use it locally on my device. I've  installed software from other github projects where an installer is present or a dmg (AutoDMG, for example), but have no idea how to install vfuse. Sorry to be such a boneheaded newb, but a step by step would really appreciated. Thanks in advance, and again my apologies for having to deal with such an idiot. :)

**Comment by chilcote** [comment]
Packages are available under releases here https://github.com/chilcote/vfuse/releases

**Comment by imasupersadpanda** [comment]
... Cripes. I'll just see myself out.



Thank you.
