### ISSUE TITLE
Unable to create the source of raw disk

### ISSUE THREAD

**Issue by adorador** [chilcote/vfuse#63]
Hello,

This week I upgraded my Mac to macOS Catalina and my VMWare Fusion to 11.5.  When I try to create new VMDK from DMGs made from AutoDMG I get the following:

```
Desktop % sudo /usr/local/vfuse/bin/vfuse -i /Volumes/SuperMac-Extreme/JAMFCompatibleVM/osx-10.14.6-18G95.apfs.dmg
Password:
Mounting /Volumes/SuperMac-Extreme/JAMFCompatibleVM/osx-10.14.6-18G95.apfs.dmg
macOS version is 10.14.6
Unmounting /Volumes/Macintosh HD 1
Using VMware Fusion path: /Applications/VMware Fusion.app
Converting DMG to VMDK
|Error: Unable to create the source raw disk: The specified device is not a valid physical disk device (20).
There is a problem with your DMG; please re-create it and try again
```

These dmg files worked prior to my upgrades with vfuse.  Are there any known issues with macOS Catalina, VMWare Fusion 11.5, and vfuse 2.2.4?  I even upgraded my AutoDMG 1.10b and tried creating a macOS Catalina dmg and ended up with the same thing:

```
Desktop % sudo /usr/local/vfuse/bin/vfuse -i /Volumes/SuperMac-Extreme/JAMFCompatibleVM/osx-10.15-19A602.apfs.dmg
Password:
Mounting /Volumes/SuperMac-Extreme/JAMFCompatibleVM/osx-10.15-19A602.apfs.dmg
macOS version is 10.15
Unmounting /Volumes/Macintosh HD 1
Using VMware Fusion path: /Applications/VMware Fusion.app
Converting DMG to VMDK
|Error: Unable to create the source raw disk: The specified device is not a valid physical disk device (20).
There is a problem with your DMG; please re-create it and try again
```
Thanks for your assistance!

**Comment by chilcote** [comment]
VMware introduced more bugs in `vdiskmanager`. I can't really be bothered to open yet another round of bugs with them about it. It's clear that our use case is not in their product roadmap.  I recommend using the [qemu option](https://github.com/chilcote/vfuse/wiki/Received-signal-11#qemu-and-not-u), which works better anyway.

**Comment by yeahdongcn** [comment]
Please try to create the VMDK with Fusion UI open. See https://kb.vmware.com/s/article/65163 for more detail. Thanks.

**Comment by NotTheVacuum** [comment]
Please note, the instructions recommend installing 'qemu-img' with brew, but you'll need to install qemu itself (no formula for just qemu-img).

**Comment by chilcote** [comment]
This issue is fixed in the latest release
